# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: La Escalera

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label:

description: > # this means to ignore newlines until "baseurl:"
  Algunos Datos Tecnicos de tecnología, asi como pequeños tutoriales.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://laescalera.github.io" # the base hostname & protocol for your site

#These settings might be able to go?
author: La Escalera 
twitter_username: 
github_username:  laescalera
company_name: 

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: false

permalink: /pub/:title.html

